apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: spring-petclinic-git
    app.kubernetes.io/component: spring-petclinic-git
    app.kubernetes.io/instance: spring-petclinic-git
    app.kubernetes.io/name: spring-petclinic-git
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
  name: spring-petclinic-git
  namespace: pet
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-petclinic-git
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic-git
        deploymentconfig: spring-petclinic-git
    spec:
      containers:
              - image: image-registry.openshift-image-registry.svc:5000/pet/spring-petclinic-git:latest
        imagePullPolicy: Always
        name: spring-petclinic-git
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
